const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Baaba Devs";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "******";
const forgetpass = "Forgot password?";
const retype = "re-enter password";
const name = "Name";
const nameHint = "Swastik Vasistha";
const login = "Login";
const signup = "Signup";
const createAcc = "or, create a new account";
const loginwith = "Login with";
const alreadyaccount = 'Already have an account? ';
const home = "Home", category = 'Category', cart = 'Cart', profile = 'account';
const search = 'Search anything... ', todaydeal = ' Todays Deal', flashsale = 'flash Sale', topseller = 'Top Seller', brand = 'Brand', topcategory = 'Top Category', featurecat = 'Featured Categroies';